#!/bin/bash
# vidpolish installer - downloads and installs the latest (or a pinned)
# vidpolish release binary.
# Usage: curl -fsSL https://raw.githubusercontent.com/shrsv/vidpolish/main/scripts/install.sh | bash
#
# - Installs to ~/.local/bin (user-writable, no sudo required).
# - Sets up PATH via an idempotent ~/.vidpolish/env shim sourced from shell
#   rc files, same as the binary needs no shell restart to be usable.
# - Runs `vidpolish deps` after install so ffmpeg is checked and
#   deep-filter/auto-editor/resvg/fonts get fetched immediately.
# - Set VIDPOLISH_VERSION=vX.Y.Z to pin a version instead of installing the
#   latest GitHub release.
# - Set VIDPOLISH_SKIP_DEPS=1 to skip the post-install `vidpolish deps` run.

set -e

REPO="shrsv/vidpolish"
INSTALL_DIR="$HOME/.local/bin"
INSTALL_PATH="$INSTALL_DIR/vidpolish"
VIDPOLISH_SKIP_DEPS="${VIDPOLISH_SKIP_DEPS:-0}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "vidpolish installer"
echo "===================="
echo ""

# Detect OS
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
case "$OS" in
    linux*)
        PLATFORM_OS="linux"
        ;;
    darwin*)
        PLATFORM_OS="darwin"
        ;;
    msys*|mingw*|cygwin*)
        echo -e "${YELLOW}Windows shell detected.${NC}"
        echo "This installer targets Linux/macOS. On Windows, download"
        echo "vidpolish-windows-amd64.exe directly from:"
        echo "  https://github.com/${REPO}/releases/latest"
        exit 1
        ;;
    *)
        echo -e "${RED}Error: unsupported operating system: $OS${NC}"
        exit 1
        ;;
esac

# Detect architecture
ARCH=$(uname -m)
case "$ARCH" in
    x86_64|amd64)
        PLATFORM_ARCH="amd64"
        ;;
    aarch64|arm64)
        PLATFORM_ARCH="arm64"
        ;;
    *)
        echo -e "${RED}Error: unsupported architecture: $ARCH${NC}"
        exit 1
        ;;
esac

PLATFORM="${PLATFORM_OS}-${PLATFORM_ARCH}"
echo -e "${GREEN}OK${NC} Detected platform: ${PLATFORM}"

# Resolve version
if [ -n "${VIDPOLISH_VERSION:-}" ]; then
    TAG="$VIDPOLISH_VERSION"
    echo -e "${GREEN}OK${NC} Using pinned version: ${TAG}"
else
    echo -n "Resolving latest vidpolish release... "
    LATEST_JSON=$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest")
    if [ $? -ne 0 ] || [ -z "$LATEST_JSON" ]; then
        echo -e "${RED}FAIL${NC}"
        echo -e "${RED}Error: failed to query GitHub for the latest release${NC}"
        exit 1
    fi
    TAG=$(echo "$LATEST_JSON" | tr -d '\n' | sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
    if [ -z "$TAG" ]; then
        echo -e "${RED}FAIL${NC}"
        echo -e "${RED}Error: could not parse tag_name from GitHub API response${NC}"
        exit 1
    fi
    echo -e "${GREEN}OK${NC}"
    echo -e "${GREEN}OK${NC} Latest version: ${TAG}"
fi

BINARY_NAME="vidpolish-${PLATFORM}"
FULL_URL="https://github.com/${REPO}/releases/download/${TAG}/${BINARY_NAME}"

mkdir -p "$INSTALL_DIR"

echo -n "Downloading ${BINARY_NAME} (${TAG})... "
TMP_FILE=$(mktemp)
HTTP_CODE=$(curl -s -L -w "%{http_code}" -o "$TMP_FILE" "$FULL_URL")

if [ "$HTTP_CODE" != "200" ]; then
    echo -e "${RED}FAIL${NC}"
    echo -e "${RED}Error: failed to download (HTTP $HTTP_CODE)${NC}"
    echo -e "${RED}URL: $FULL_URL${NC}"
    rm -f "$TMP_FILE"
    exit 1
fi
if [ ! -s "$TMP_FILE" ]; then
    echo -e "${RED}FAIL${NC}"
    echo -e "${RED}Error: downloaded file is empty${NC}"
    rm -f "$TMP_FILE"
    exit 1
fi
echo -e "${GREEN}OK${NC}"

echo -n "Installing to ${INSTALL_PATH}... "
if ! mv "$TMP_FILE" "$INSTALL_PATH"; then
    echo -e "${RED}FAIL${NC}"
    echo -e "${RED}Error: failed to install to ${INSTALL_PATH}${NC}"
    rm -f "$TMP_FILE"
    exit 1
fi
chmod +x "$INSTALL_PATH"
echo -e "${GREEN}OK${NC}"

if [ "$PLATFORM_OS" = "darwin" ]; then
    xattr -d com.apple.quarantine "$INSTALL_PATH" 2>/dev/null || true
fi

# ---------------------------------------------------------------------------
# PATH management — idempotent env shim + shell rc source lines
# ---------------------------------------------------------------------------
VIDPOLISH_ENV_DIR="$HOME/.vidpolish"
VIDPOLISH_ENV_FILE="$VIDPOLISH_ENV_DIR/env"

mkdir -p "$VIDPOLISH_ENV_DIR"
cat > "$VIDPOLISH_ENV_FILE" << 'ENVEOF'
#!/bin/sh
# vidpolish shell setup (auto-generated by the vidpolish installer)
case ":${PATH}:" in
    *:"$HOME/.local/bin":*)
        ;;
    *)
        export PATH="$HOME/.local/bin:$PATH"
        ;;
esac
ENVEOF
chmod +x "$VIDPOLISH_ENV_FILE"

add_source_line() {
    local rcfile="$1"
    if [ -f "$rcfile" ] && [ -r "$rcfile" ]; then
        if ! grep -qF '/.vidpolish/env' "$rcfile"; then
            echo "" >> "$rcfile"
            echo "# Added by vidpolish installer" >> "$rcfile"
            echo ". \"\$HOME/.vidpolish/env\"" >> "$rcfile"
            echo -e "  ${GREEN}OK${NC} Updated $rcfile"
        fi
    fi
}

create_source_line() {
    local rcfile="$1"
    if [ ! -f "$rcfile" ]; then
        echo "# Added by vidpolish installer" > "$rcfile"
        echo ". \"\$HOME/.vidpolish/env\"" >> "$rcfile"
        echo -e "  ${GREEN}OK${NC} Created $rcfile"
    else
        add_source_line "$rcfile"
    fi
}

echo "Setting up PATH..."
create_source_line "$HOME/.profile"

CURRENT_SHELL="$(basename "${SHELL:-/bin/sh}")"
case "$CURRENT_SHELL" in
    bash)
        add_source_line "$HOME/.bashrc"
        add_source_line "$HOME/.bash_profile"
        ;;
    zsh)
        create_source_line "$HOME/.zshenv"
        add_source_line "$HOME/.zshrc"
        ;;
    fish)
        FISH_CONF_DIR="$HOME/.config/fish/conf.d"
        FISH_CONF="$FISH_CONF_DIR/vidpolish.fish"
        mkdir -p "$FISH_CONF_DIR"
        if [ ! -f "$FISH_CONF" ] || ! grep -qF '.local/bin' "$FISH_CONF"; then
            cat > "$FISH_CONF" << 'FISHEOF'
# vidpolish shell setup (auto-generated by the vidpolish installer)
if not contains -- $HOME/.local/bin $PATH
    set -gx PATH $HOME/.local/bin $PATH
end
FISHEOF
            echo -e "  ${GREEN}OK${NC} Created $FISH_CONF"
        fi
        ;;
    *)
        ;;
esac

export PATH="$HOME/.local/bin:$PATH"

echo ""
echo -e "${GREEN}OK Installation complete!${NC}"
echo ""
"$INSTALL_PATH" version

if [ "$VIDPOLISH_SKIP_DEPS" = "1" ]; then
    echo -e "${YELLOW}Skipping dependency fetch because VIDPOLISH_SKIP_DEPS=1${NC}"
else
    echo ""
    echo "Fetching dependencies (ffmpeg check, deep-filter, auto-editor, resvg, font)..."
    "$INSTALL_PATH" deps || echo -e "${YELLOW}(warning) some dependencies could not be resolved; see messages above.${NC}"
fi

echo ""
echo -e "To start using vidpolish in your ${YELLOW}current${NC} terminal, run:"
echo ""
echo -e "  ${GREEN}source ~/.vidpolish/env${NC}"
echo ""
echo "New terminal sessions will pick it up automatically."
echo ""
echo "Get started:"
echo "  vidpolish process <input.mp4>   # polish a raw recording"
echo "  vidpolish ui                    # open the local Projects UI"
